title: My blog
author:
  name: Joostvv
  email: joost_vv@hotmail.com
description: > # Blog in which small projects are documented

show_excerpts: true

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    github:  joostvv

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
   - _layouts/home.md

include:
   - _layouts

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

exclude:
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
